// packages/frontend/src/components/CreateMeetingDialog.svelte
<script lang="ts">
	interface Props {
		isOpen: boolean;
		onOpenChange: (isOpen: boolean) => void;
	}

	let { isOpen, onOpenChange }: Props = $props();

	let name = $state('');
	let description = $state('');
	let isSubmitting = $state(false);

	const handleSubmit = async () => {
		if (!name.trim()) {
			alert('Meeting name is required');
			return;
		}

		isSubmitting = true;

		try {
			const meetingData = {
				name: name.trim(),
				description: description.trim() || undefined,
				startTime: new Date().toISOString(),
				duration: 60
			};

			// This will be handled by the parent component
			// We'll dispatch a custom event instead
			const event = new CustomEvent('create-meeting', { detail: meetingData });
			dispatchEvent(event);

			// Reset form and close
			name = '';
			description = '';
			onOpenChange(false);
		} catch (error) {
			console.error('Create meeting error:', error);
			alert('Failed to create meeting. Please try again.');
		} finally {
			isSubmitting = false;
		}
	};

	const handleClose = () => {
		if (!isSubmitting) {
			onOpenChange(false);
		}
	};
</script>

{#if isOpen}
	<div class="fixed inset-0 z-50 flex items-center justify-center">
		<div class="fixed inset-0 bg-black/50" onclick={handleClose}></div>
		<div class="relative bg-background rounded-lg shadow-lg p-6 w-full max-w-md">
			<h2 class="text-lg font-semibold mb-4">Create New Meeting</h2>
			<p class="text-sm text-muted-foreground mb-4">
				Give your meeting a name to get started. You can invite others later.
			</p>
			
			<form onsubmit={(e) => { e.preventDefault(); handleSubmit(); }} class="grid gap-4">
				<div>
					<label for="name" class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
						Name
					</label>
					<input
						id="name"
						type="text"
						placeholder="Team Sync"
						bind:value={name}
						class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 mt-2"
						required
					/>
				</div>
				
				<div>
					<label for="description" class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
						Description (optional)
					</label>
					<textarea
						id="description"
						placeholder="Meeting description"
						bind:value={description}
						class="flex min-h-[60px] w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 mt-2"
					></textarea>
				</div>
			</form>
			
			<div class="flex justify-end mt-6">
				<button
					type="button"
					onclick={handleClose}
					class="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-9 px-4 py-2 mr-2"
					disabled={isSubmitting}
				>
					Cancel
				</button>
				<button
					type="submit"
					onclick={handleSubmit}
					class="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-9 px-4 py-2"
					disabled={isSubmitting}
				>
					{isSubmitting ? 'Creating...' : 'Create & Join Meeting'}
				</button>
			</div>
		</div>
	</div>
{/if}

// src/components/create-meeting-dialog.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormMessage,
} from "@/components/ui/form";
import { useAuthContext } from "@/contexts/auth-context";
import { useToast } from "@/hooks/use-toast";
import { CreateMeetingRequest } from "@/lib/meeting-service";

const createMeetingSchema = z.object({
  name: z
    .string()
    .min(3, { message: "Meeting title must be at least 3 characters" }),
  description: z.string().optional(),
  startTime: z.string().optional(),
  duration: z.number().min(15).max(480).optional(),
});

type CreateMeetingFormValues = z.infer<typeof createMeetingSchema>;

interface CreateMeetingDialogProps {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
}

export function CreateMeetingDialog({
  isOpen,
  onOpenChange,
}: CreateMeetingDialogProps) {
  const router = useRouter();
  const { user } = useAuthContext();
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const form = useForm<CreateMeetingFormValues>({
    resolver: zodResolver(createMeetingSchema),
    defaultValues: {
      name: "",
      description: "",
      startTime: new Date().toISOString(),
      duration: 60,
    },
  });

  const onSubmit = async (data: CreateMeetingFormValues) => {
    if (!user) {
      toast({
        variant: "destructive",
        title: "Error",
        description: "You must be logged in to create a meeting.",
      });
      return;
    }

    setIsSubmitting(true);

    try {
      const meetingData: CreateMeetingRequest = {
        name: data.name,
        description: data.description || undefined,
        startTime: data.startTime || new Date().toISOString(),
        duration: data.duration || 60,
      };

      // Import meetingService directly to get the created meeting
      const { meetingService } = await import("@/lib/meeting-service");
      const meeting = await meetingService.createMeeting(meetingData);

      toast({
        title: "Success!",
        description: "Your meeting has been created.",
      });

      onOpenChange(false);
      form.reset();
      // Redirect to the new meeting room
      router.push(`/meeting/${meeting.id}`);
    } catch (error: any) {
      console.error("Error creating meeting:", error);
      toast({
        variant: "destructive",
        title: "Uh oh! Something went wrong.",
        description:
          error.message || "Could not create the meeting. Please try again.",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Create New Meeting</DialogTitle>
          <DialogDescription>
            Give your meeting a name to get started. You can invite others
            later.
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form
            onSubmit={form.handleSubmit(onSubmit)}
            className="grid gap-4 py-4"
          >
            <FormField
              control={form.control}
              name="name"
              render={({ field }) => (
                <FormItem className="grid grid-cols-4 items-center gap-4">
                  <Label htmlFor="name" className="text-right">
                    Name
                  </Label>
                  <FormControl>
                    <Input
                      id="name"
                      placeholder="Team Sync"
                      className="col-span-3"
                      {...field}
                    />
                  </FormControl>
                  <div className="col-span-4 col-start-2">
                    <FormMessage />
                  </div>
                </FormItem>
              )}
            />
            <DialogFooter>
              <Button type="submit" disabled={isSubmitting}>
                {isSubmitting ? "Creating..." : "Create & Join Meeting"}
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
