// components/user-nav.tsx
"use client";

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import Link from "next/link";
import { useAuthContext } from "@/contexts/auth-context";
import { useRouter } from "next/navigation";

export function UserNav() {
  const { user, loading, logout } = useAuthContext();
  const router = useRouter();

  const userAvatar = `https://picsum.photos/seed/${
    user?.id || "user-nav"
  }/100/100`;

  const handleLogout = async () => {
    try {
      await logout();
      router.push("/");
    } catch (error) {
      console.error("Logout error:", error);
      // Tetap redirect meskipun ada error
      router.push("/");
    }
  };

  if (loading) {
    return <div className="h-9 w-9 rounded-full bg-muted animate-pulse" />;
  }

  if (!user) {
    return (
      <Link href="/" passHref>
        <Button variant="outline">Login</Button>
      </Link>
    );
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" className="relative h-8 w-8 rounded-full">
          <Avatar className="h-9 w-9">
            <AvatarImage
              src={userAvatar}
              alt={user.username || "User"}
              data-ai-hint="person face"
            />
            <AvatarFallback>
              {user.username?.charAt(0).toUpperCase() ||
                user.email?.charAt(0).toUpperCase() ||
                "U"}
            </AvatarFallback>
          </Avatar>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="w-56" align="end" forceMount>
        <DropdownMenuLabel className="font-normal">
          <div className="flex flex-col space-y-1">
            <p className="text-sm font-medium leading-none">
              {user.username || "User"}
            </p>
            <p className="text-xs leading-none text-muted-foreground">
              {user.email}
            </p>
          </div>
        </DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuGroup>
          <DropdownMenuItem>Profile</DropdownMenuItem>
          <DropdownMenuItem>Settings</DropdownMenuItem>
        </DropdownMenuGroup>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={handleLogout}>Logout</DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

// packages/frontend/src/components/UserNav.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { authStore, type User } from '../lib/stores/auth.store';

	let user: User | null = $state(null);
	let loading: boolean = $state(true);

	// Subscribe to auth store changes
	$effect(() => {
		const unsubscribe = authStore.subscribe((state) => {
			user = state.user;
			loading = state.loading;
		});

		return unsubscribe;
	});

	const handleLogout = async () => {
		try {
			await authStore.logout();
			goto('/');
		} catch (error) {
			console.error('Logout error:', error);
			goto('/');
		}
	};
</script>

{#if loading}
	<div class="h-9 w-9 rounded-full bg-muted animate-pulse"></div>
{:else if !user}
	<button
		onclick={() => goto('/')}
		class="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-9 px-4 py-2"
	>
		Login
	</button>
{:else}
	<div class="relative">
		<button class="inline-flex items-center justify-center rounded-full h-8 w-8 bg-muted hover:bg-accent transition-colors">
			<div class="relative h-9 w-9 rounded-full">
				<div class="flex h-full w-full items-center justify-center rounded-full bg-muted">
					{user.email?.charAt(0).toUpperCase() || 'U'}
				</div>
			</div>
		</button>
		
		<!-- Dropdown menu - simplified for now -->
		<div class="absolute right-0 mt-2 w-56 rounded-md bg-popover p-1 text-popover-foreground shadow-md">
			<div class="px-2 py-1.5 text-sm">
				<div class="font-medium">{user.username || 'User'}</div>
				<div class="text-muted-foreground text-xs">{user.email}</div>
			</div>
			<hr class="my-1 border-border" />
			<button
				onclick={handleLogout}
				class="relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none transition-colors hover:bg-accent hover:text-accent-foreground w-full text-left"
			>
				Logout
			</button>
		</div>
	</div>
{/if}
